name = "AtomBase"
uuid = "640af26c-ec64-41b7-8129-95595126c51b"
authors = ["Northwemko <yinyangxiangsheng@gmail.com> and contributors"]
version = "0.1.0"

[deps]
HalfIntegers = "f0d1745a-41c9-11e9-1dd9-e5d34d218721"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
HalfIntegers = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
